version: "3"
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nestauth
      - POSTGRES_PASSWORD=pgpassword
    volumes:
      - pgauth:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis      

volumes:
  pgauth:
  redisdata:
